/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 0e6eca4f-5376-490e-bd44-9664dc5c078c

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.

-/

/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 453ac437-6b88-457f-88ef-9b180f5fe600

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.

-/

/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e25e4ca2-a4b3-4e1c-ac96-e7ea34020350

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.

-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of the function h_N(x) used in the coupling.
-/
noncomputable def h (N : ℝ) (x : ℝ) : ℝ :=
  - Real.log (N * (1 - Real.exp (-Real.exp (-x) / N))) - x

/-
Lemma 1: Convexity and bounds for h_N(x).
-/
theorem lemma_1 (N : ℝ) (hN : 1 ≤ N) :
    ConvexOn ℝ Set.univ (h N) ∧
    (∀ x, 0 < h N x ∧ h N x ≤ Real.exp (-x) / N) ∧
    (∀ x, 0 < x → Real.exp (-x) / (3 * N) ≤ h N x) := by
      unfold ConvexOn h;
      refine' ⟨ _, _, _ ⟩;
      · -- We'll use the fact that $h_N(x)$ is the composition of convex functions.
        have h_convex : ConvexOn ℝ Set.univ (fun x => -Real.log (1 - Real.exp (-Real.exp (-x) / N))) := by
          apply_rules [ convexOn_of_deriv2_nonneg, convex_univ ];
          · field_simp;
            exact continuousOn_of_forall_continuousAt fun x hx => ContinuousAt.neg <| ContinuousAt.log ( continuousAt_const.sub <| Real.continuous_exp.continuousAt.comp <| ContinuousAt.neg <| ContinuousAt.div_const ( Real.continuous_exp.continuousAt.comp <| ContinuousAt.neg continuousAt_id ) _ ) <| ne_of_gt <| sub_pos_of_lt <| Real.exp_lt_one_iff.mpr <| neg_lt_zero.mpr <| by positivity;
          · field_simp;
            exact DifferentiableOn.neg ( DifferentiableOn.log ( DifferentiableOn.sub ( differentiableOn_const _ ) ( DifferentiableOn.exp ( DifferentiableOn.neg ( DifferentiableOn.div_const ( DifferentiableOn.exp ( differentiableOn_id.neg ) ) _ ) ) ) ) fun x hx => ne_of_gt ( sub_pos.mpr ( Real.exp_lt_one_iff.mpr ( neg_lt_zero.mpr ( by positivity ) ) ) ) );
          · refine' DifferentiableOn.congr _ _;
            use fun x => ( Real.exp ( -Real.exp ( -x ) / N ) * Real.exp ( -x ) / N ) / ( 1 - Real.exp ( -Real.exp ( -x ) / N ) );
            · refine' DifferentiableOn.div _ _ _ <;> norm_num [ DifferentiableOn.exp, DifferentiableOn.neg, DifferentiableOn.mul, DifferentiableOn.div, differentiableOn_id, differentiableOn_const ];
              · fun_prop (disch := norm_num);
              · exact DifferentiableOn.exp ( DifferentiableOn.div_const ( DifferentiableOn.neg ( DifferentiableOn.exp ( differentiableOn_id.neg ) ) ) _ );
              · exact fun x => sub_ne_zero_of_ne <| Ne.symm <| by norm_num ; positivity;
            · intro x hx; norm_num [ Real.exp_ne_zero, Real.exp_neg, Real.differentiableAt_exp, ne_of_gt ( show 0 < 1 - Real.exp ( -Real.exp ( -x ) / N ) from sub_pos.mpr <| Real.exp_lt_one_iff.mpr <| by { exact div_neg_of_neg_of_pos ( neg_lt_zero.mpr <| Real.exp_pos _ ) <| by positivity } ) ] ; ring;
              convert congr_arg Neg.neg ( HasDerivAt.deriv ( HasDerivAt.log ( HasDerivAt.sub ( hasDerivAt_const _ _ ) ( HasDerivAt.exp ( HasDerivAt.neg ( HasDerivAt.mul ( HasDerivAt.inv ( Real.hasDerivAt_exp _ ) <| ne_of_gt <| Real.exp_pos _ ) <| hasDerivAt_const _ _ ) ) ) ) <| show ( 1 - Real.exp ( - ( ( Real.exp x ) ⁻¹ * N⁻¹ ) ) ) ≠ 0 from sub_ne_zero.mpr <| Ne.symm <| by norm_num; positivity ) ) using 1 ; norm_num ; ring;
              norm_num [ sq, mul_assoc, Real.exp_ne_zero ];
          · -- Let's calculate the first derivative of $h_N(x)$.
            have h_deriv : ∀ x, deriv (fun x => -Real.log (1 - Real.exp (-Real.exp (-x) / N))) x = (Real.exp (-x) / N) * (Real.exp (-Real.exp (-x) / N)) / (1 - Real.exp (-Real.exp (-x) / N)) := by
              intro x; norm_num [ Real.exp_ne_zero, Real.exp_neg, Real.differentiableAt_exp, div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, ne_of_gt ( show 0 < 1 - Real.exp ( -Real.exp ( -x ) / N ) from sub_pos.mpr <| by rw [ Real.exp_lt_one_iff ] ; exact div_neg_of_neg_of_pos ( neg_neg_of_pos <| Real.exp_pos _ ) <| by positivity ) ] ;
              norm_num [ Real.exp_ne_zero, Real.differentiableAt_exp, mul_comm, ne_of_gt ( show 0 < 1 - ( Real.exp ( N⁻¹ * ( Real.exp x ) ⁻¹ ) ) ⁻¹ from sub_pos.mpr <| inv_lt_one_of_one_lt₀ <| by norm_num; positivity ) ] ; ring;
              norm_num [ sq, mul_assoc, Real.exp_ne_zero ];
            aesop;
            refine' ( HasDerivAt.deriv _ ) |> fun h => h.symm ▸ _;
            convert HasDerivAt.div ( HasDerivAt.mul ( HasDerivAt.div_const ( HasDerivAt.exp ( hasDerivAt_neg x ) ) _ ) ( HasDerivAt.exp ( HasDerivAt.div_const ( HasDerivAt.neg ( HasDerivAt.exp ( hasDerivAt_neg x ) ) ) _ ) ) ) ( HasDerivAt.sub ( hasDerivAt_const _ _ ) ( HasDerivAt.exp ( HasDerivAt.div_const ( HasDerivAt.neg ( HasDerivAt.exp ( hasDerivAt_neg x ) ) ) _ ) ) ) _ using 1;
            · exact ne_of_gt ( sub_pos_of_lt ( Real.exp_lt_one_iff.mpr ( by exact div_neg_of_neg_of_pos ( neg_neg_of_pos ( Real.exp_pos _ ) ) ( by positivity ) ) ) );
            · rw [ le_div_iff₀ ] <;> norm_num;
              · ring_nf;
                nlinarith only [ show 0 ≤ Real.exp ( -x ) * N⁻¹ * Real.exp ( - ( Real.exp ( -x ) * N⁻¹ ) ) by positivity, show 0 ≤ Real.exp ( -x ) ^ 2 * N⁻¹ ^ 2 * Real.exp ( - ( Real.exp ( -x ) * N⁻¹ ) ) by positivity, Real.exp_pos ( -x ), Real.exp_pos ( - ( Real.exp ( -x ) * N⁻¹ ) ), Real.add_one_le_exp ( - ( Real.exp ( -x ) * N⁻¹ ) ), Real.add_one_le_exp ( -x ) ];
              · exact pow_pos ( sub_pos_of_lt ( by rw [ Real.exp_lt_one_iff ] ; exact div_neg_of_neg_of_pos ( neg_neg_of_pos ( Real.exp_pos _ ) ) ( by positivity ) ) ) _;
        aesop;
        · exact convex_univ;
        · have := h_convex.2 ( Set.mem_univ x ) ( Set.mem_univ y ) a_1 a_2 a_3 ; aesop;
          rw [ Real.log_mul ( by positivity ) ( by exact ne_of_gt <| sub_pos.mpr <| Real.exp_lt_one_iff.mpr <| by exact div_neg_of_neg_of_pos ( neg_lt_zero.mpr <| Real.exp_pos _ ) <| by positivity ), Real.log_mul ( by positivity ) ( by exact ne_of_gt <| sub_pos.mpr <| Real.exp_lt_one_iff.mpr <| by exact div_neg_of_neg_of_pos ( neg_lt_zero.mpr <| Real.exp_pos _ ) <| by positivity ) ] at * ; aesop;
          rw [ Real.log_mul ( by positivity ) ( by exact ne_of_gt <| sub_pos.mpr <| Real.exp_lt_one_iff.mpr <| by exact div_neg_of_neg_of_pos ( neg_lt_zero.mpr <| Real.exp_pos _ ) <| by positivity ) ] ; nlinarith [ Real.log_le_sub_one_of_pos <| show 0 < N by positivity ] ;
      · aesop;
        · rw [ lt_neg, Real.log_lt_iff_lt_exp ];
          · nlinarith [ Real.exp_pos ( -Real.exp ( -x ) / N ), Real.exp_neg ( -Real.exp ( -x ) / N ), mul_inv_cancel₀ ( ne_of_gt ( Real.exp_pos ( -Real.exp ( -x ) / N ) ) ), Real.add_one_lt_exp ( show -Real.exp ( -x ) / N ≠ 0 by exact div_ne_zero ( neg_ne_zero.mpr ( ne_of_gt ( Real.exp_pos _ ) ) ) ( by positivity ) ), Real.exp_pos ( -x ), Real.exp_neg x, mul_div_cancel₀ ( -Real.exp ( -x ) ) ( by positivity : ( N : ℝ ) ≠ 0 ) ];
          · exact mul_pos ( by positivity ) ( sub_pos_of_lt ( Real.exp_lt_one_iff.mpr ( by exact div_neg_of_neg_of_pos ( neg_lt_zero.mpr ( Real.exp_pos _ ) ) ( by positivity ) ) ) );
        · rw [ neg_le ];
          rw [ ← Real.log_exp ( - ( Real.exp ( -x ) / N + x ) ) ];
          gcongr;
          ring_nf;
          rw [ sub_eq_add_neg, Real.exp_add ];
          nlinarith [ inv_pos.mpr ( zero_lt_one.trans_le hN ), mul_inv_cancel₀ ( ne_of_gt ( zero_lt_one.trans_le hN ) ), Real.exp_pos ( -x ), Real.exp_pos ( - ( Real.exp ( -x ) * N⁻¹ ) ), Real.exp_neg ( Real.exp ( -x ) * N⁻¹ ), mul_inv_cancel₀ ( ne_of_gt ( Real.exp_pos ( Real.exp ( -x ) * N⁻¹ ) ) ), Real.add_one_le_exp ( -x ), Real.add_one_le_exp ( - ( Real.exp ( -x ) * N⁻¹ ) ), Real.add_one_le_exp ( Real.exp ( -x ) * N⁻¹ ), Real.exp_neg ( -x ), mul_inv_cancel₀ ( ne_of_gt ( Real.exp_pos ( -x ) ) ) ];
      · -- Let $y = \frac{e^{-x}}{N}$. Since $x > 0$ and $N \geq 1$, we have $0 < y \leq 1$.
        intro x hx_pos
        set y := Real.exp (-x) / N
        have hy_pos : 0 < y := by
          positivity
        have hy_le_one : y ≤ 1 := by
          exact div_le_one_of_le₀ ( le_trans ( Real.exp_le_one_iff.mpr ( neg_nonpos.mpr hx_pos.le ) ) hN ) ( by positivity );
        -- We want to prove $h_N(x) \geq \frac{y}{3}$, which is equivalent to $\frac{1 - e^{-y}}{y} \leq e^{-y/3}$.
        suffices h_ineq : (1 - Real.exp (-y)) / y ≤ Real.exp (-y / 3) by
          -- Taking the natural logarithm of both sides of the inequality $\frac{1 - e^{-y}}{y} \leq e^{-y/3}$, we get $-\ln\left(\frac{1 - e^{-y}}{y}\right) \geq \frac{y}{3}$.
          have h_log_ineq : -Real.log ((1 - Real.exp (-y)) / y) ≥ y / 3 := by
            have := Real.log_le_log ( div_pos ( sub_pos.mpr <| Real.exp_lt_one_iff.mpr <| neg_lt_zero.mpr hy_pos ) hy_pos ) h_ineq ; norm_num at * ; linarith;
          rw [ Real.log_div ] at h_log_ineq <;> aesop;
          · rw [ Real.log_mul ] at * <;> aesop;
            · rw [ Real.log_div ( by positivity ) ( by positivity ), Real.log_exp ] at h_log_ineq ; ring_nf at * ; linarith;
            · exact absurd a <| ne_of_gt <| sub_pos_of_lt <| Real.exp_lt_one_iff.mpr <| by ring_nf; norm_num; positivity;
          · linarith;
        -- Consider $g(t) = 1 - t + \frac{t^2}{2} - \frac{t^3}{6} - e^{-t}$ for $t \geq 0$. Then $g'''(t) = -1 + e^{-t} \leq 0$, so $g(t) \leq 0$ for all $t \geq 0$.
        have h_g : ∀ t : ℝ, 0 ≤ t → 1 - t + t^2 / 2 - t^3 / 6 ≤ Real.exp (-t) := by
          -- Let's choose any $t \geq 0$ and derive the inequality.
          intro t ht
          have h_deriv : ∀ t : ℝ, 0 ≤ t → deriv (fun t => Real.exp t * (1 - t + t^2 / 2 - t^3 / 6)) t ≤ 0 := by
            intro t ht; norm_num [ Real.differentiableAt_exp, mul_comm, sub_add, add_assoc ] ; ring_nf; norm_num [ Real.exp_pos ] ;
            positivity;
          -- Since $g(t)$ is differentiable and its derivative is non-positive for $t \geq 0$, we can apply the Mean Value Theorem to $g(t)$ on the interval $[0, t]$.
          have h_mvt : ∀ t : ℝ, 0 < t → ∃ c ∈ Set.Ioo 0 t, deriv (fun t => Real.exp t * (1 - t + t^2 / 2 - t^3 / 6)) c = (Real.exp t * (1 - t + t^2 / 2 - t^3 / 6) - Real.exp 0 * (1 - 0 + 0^2 / 2 - 0^3 / 6)) / (t - 0) := by
            intros t ht_pos;
            have := exists_deriv_eq_slope ( f := fun t => Real.exp t * ( 1 - t + t ^ 2 / 2 - t ^ 3 / 6 ) ) ht_pos;
            exact this ( Continuous.continuousOn <| by exact Continuous.mul ( Real.continuous_exp ) <| by exact Continuous.sub ( Continuous.add ( continuous_const.sub continuous_id' ) <| continuous_pow 2 |> Continuous.div_const <| 2 ) <| continuous_pow 3 |> Continuous.div_const <| 6 ) ( Differentiable.differentiableOn <| by exact Differentiable.mul ( Real.differentiable_exp ) <| by exact Differentiable.sub ( Differentiable.add ( differentiable_const _ |> Differentiable.sub <| differentiable_id' ) <| differentiable_pow 2 |> Differentiable.div_const <| 2 ) <| differentiable_pow 3 |> Differentiable.div_const <| 6 );
          cases lt_or_eq_of_le ht <;> aesop;
          obtain ⟨ c, ⟨ hc₁, hc₂ ⟩, hc ⟩ := h_mvt t h ; have := h_deriv c hc₁.le ; rw [ hc ] at this ; rw [ div_le_iff₀ <| by positivity ] at this ; nlinarith [ Real.exp_pos t, Real.exp_neg t, mul_inv_cancel₀ <| ne_of_gt <| Real.exp_pos t ];
        -- Hence $1 - e^{-t} \leq t - \frac{t^2}{2} + \frac{t^3}{6}$ so $\frac{1 - e^{-t}}{t} \leq 1 - \frac{t}{2} + \frac{t^2}{6} \leq 1 - \frac{t}{3}$ where the last inequality holds whenever $0 \leq t \leq 1$.
        have h_ineq : ∀ t : ℝ, 0 ≤ t ∧ t ≤ 1 → (1 - Real.exp (-t)) / t ≤ 1 - t / 3 := by
          intro t ht; rcases eq_or_lt_of_le ht.1 with ( rfl | ht₁ ) <;> [ norm_num; rw [ div_le_iff₀ ht₁ ] ] ; nlinarith [ h_g t ht.1 ] ;
        exact le_trans ( h_ineq y ⟨ hy_pos.le, hy_le_one ⟩ ) ( by linarith [ Real.add_one_le_exp ( -y / 3 ) ] )

/-
Lemma 2: Perturbation bounds for LPP models.
-/
theorem lemma_2 {Pi : Type*} [Fintype Pi] [Nonempty Pi]
    (S_A S_B : Pi → ℝ) (pi_star : Pi)
    (h_pi_star : ∀ p, S_A p ≤ S_A pi_star) :
    let M_A := S_A pi_star
    let M_AB := (Finset.univ.image (fun p => S_A p + S_B p)).max' (Finset.univ_nonempty.image _)
    let m_B := (Finset.univ.image S_B).min' (Finset.univ_nonempty.image _)
    let M_B := (Finset.univ.image S_B).max' (Finset.univ_nonempty.image _)
    m_B ≤ S_B pi_star ∧
    S_B pi_star ≤ M_AB - M_A ∧
    M_AB - M_A ≤ M_B := by
      aesop;
      · exact Finset.min'_le _ _ ( Finset.mem_image_of_mem _ ( Finset.mem_univ _ ) );
      · exact le_tsub_of_add_le_left ( by simpa [ add_comm ] using Finset.le_max' _ _ ( Finset.mem_image_of_mem ( fun p => S_A p + S_B p ) ( Finset.mem_univ pi_star ) ) );
      · linarith [ h_pi_star a, Finset.le_max' ( Finset.image S_B Finset.univ ) ( S_B a ) ( Finset.mem_image_of_mem _ ( Finset.mem_univ a ) ) ]

/-
Definitions of GridPoint, Edge, GridPath, and IsValidPath.
-/
/-- A point in the grid $\mathbb{N}^2$. -/
def GridPoint := ℕ × ℕ

/-- An edge in the grid. -/
def Edge := GridPoint × GridPoint

/-- An edge is up-right if it goes from $(x,y)$ to $(x+1,y)$ or $(x,y+1)$. -/
def is_up_right (e : Edge) : Prop :=
  (e.2.1 = e.1.1 + 1 ∧ e.2.2 = e.1.2) ∨ (e.2.1 = e.1.1 ∧ e.2.2 = e.1.2 + 1)

/-- A path is a list of edges. -/
def GridPath := List Edge

/-- A path is valid from start to end if it is a sequence of connected up-right edges. -/
inductive IsValidPath : GridPoint → GridPoint → GridPath → Prop
  | nil (p : GridPoint) : IsValidPath p p []
  | cons (p q r : GridPoint) (l : GridPath) (h_edge : is_up_right (p, q)) (h_path : IsValidPath q r l) :
    IsValidPath p r ((p, q) :: l)

/-
The set of all valid paths from $(0,0)$ to $(m,n)$.
-/
noncomputable def paths (m n : ℕ) : Finset GridPath :=
  let s := { l : GridPath | IsValidPath (0,0) (m,n) l }
  have h_finite : s.Finite := by
    -- Each valid path from $(0,0)$ to $(m,n)$ can be described by a sequence of moves, either right or down.
    have h_paths_finite : ∀ p q : GridPoint, Set.Finite {l : GridPath | IsValidPath p q l ∧ l.length ≤ m + n} := by
      intro p q;
      -- Each valid path from $(0,0)$ to $(m,n)$ can be described by a sequence of moves, either right or down. The number of such sequences is finite.
      have h_paths_finite : ∀ p q : GridPoint, ∀ k : ℕ, Set.Finite { l : GridPath | IsValidPath p q l ∧ l.length = k } := by
        intro p q k
        induction' k with k ih generalizing p q;
        · refine Set.Finite.subset ( Set.finite_singleton [ ] ) ?_ ; aesop;
        · have h_finite_edges : Set.Finite {e : Edge | is_up_right e ∧ e.1 = p} := by
            exact Set.Finite.subset ( Set.toFinite { ( p, ( p.1 + 1, p.2 ) ), ( p, ( p.1, p.2 + 1 ) ) } ) fun e he => by cases he; aesop;
          refine' Set.Finite.subset ( h_finite_edges.biUnion fun e he => ih e.2 q |> Set.Finite.image fun l => ( e :: l ) ) _;
          intro l hl; rcases hl with ⟨ hl₁, hl₂ ⟩ ; induction' l with e l ih <;> aesop;
          · cases hl₁ ; aesop;
            exact ⟨ h_path, rfl ⟩;
          · cases hl₁ ; aesop;
          · cases hl₁ ; aesop;
      exact Set.Finite.subset ( Set.Finite.biUnion ( Set.finite_Iic ( m + n ) ) fun k hk => h_paths_finite p q k ) fun l hl => by aesop;
    refine h_paths_finite ( 0, 0 ) ( m, n ) |> Set.Finite.subset <| fun l hl => ?_;
    -- By definition of IsValidPath, each path from (0,0) to (m,n) consists of exactly m + n steps.
    have h_length : ∀ p q : GridPoint, ∀ l : GridPath, IsValidPath p q l → l.length = q.1 + q.2 - p.1 - p.2 := by
      intros p q l hl; induction hl <;> aesop;
      rcases h_edge with ( ⟨ h₁, h₂ ⟩ | ⟨ h₁, h₂ ⟩ ) <;> simp_all +decide [ Nat.sub_sub ];
      · have h_length : ∀ p q : GridPoint, ∀ l : GridPath, IsValidPath p q l → p.1 ≤ q.1 ∧ p.2 ≤ q.2 := by
          intros p q l hl; induction hl <;> aesop;
          · cases h_edge <;> aesop;
            linarith;
          · cases h_edge <;> aesop;
            linarith;
        grind;
      · rw [ tsub_add_eq_add_tsub ];
        · omega;
        · have h_length : ∀ p q : GridPoint, ∀ l : GridPath, IsValidPath p q l → p.1 ≤ q.1 ∧ p.2 ≤ q.2 := by
            intros p q l hl; induction hl <;> aesop;
            · cases h_edge <;> aesop ; linarith;
            · cases h_edge <;> aesop ; linarith;
          linarith [ h_length _ _ _ h_path ];
    exact ⟨ hl, h_length _ _ _ hl ▸ by norm_num ⟩
  h_finite.toFinset

/-
The set of paths from (0,0) to (m,n) is nonempty.
-/
lemma paths_nonempty (m n : ℕ) : (paths m n).Nonempty := by
  -- We'll use induction to prove that there is always a valid path from $(0,0)$ to $(m,n)$.
  induction' m with m ih generalizing n;
  · use List.map ( fun i => ( ( 0, i ), ( 0, i + 1 ) ) ) ( List.range n );
    unfold paths; aesop;
    induction' n with n ih <;> simp_all +decide [ List.range_succ ];
    · constructor;
    · convert IsValidPath.cons _ _ _ _ _ _ using 1;
      rotate_left;
      exact ( 0, 1 );
      exact List.map ( fun i => ( ( 0, i + 1 ), 0, i + 2 ) ) ( List.range n );
      · exact Or.inr ⟨ rfl, rfl ⟩;
      · have h_valid : ∀ (p q : GridPoint) (l : GridPath), IsValidPath p q l → IsValidPath (p.1, p.2 + 1) (q.1, q.2 + 1) (List.map (fun e => ((e.1.1, e.1.2 + 1), (e.2.1, e.2.2 + 1))) l) := by
          intros p q l hl; induction hl <;> aesop;
          · constructor;
          · apply_rules [ IsValidPath.cons ];
            cases h_edge <;> aesop;
            · exact Or.inl ⟨ rfl, rfl ⟩;
            · exact Or.inr ⟨ rfl, rfl ⟩;
        convert h_valid _ _ _ ih using 1;
        induction ( List.range n ) <;> aesop;
      · exact Nat.recOn n ( by norm_num ) fun n ih => by simp_all +decide [ List.range_succ ] ;
  · by_contra h_empty;
    obtain ⟨l, hl⟩ : ∃ l : GridPath, IsValidPath (0, 0) (m, n) l := by
      specialize ih n; unfold paths at ih; aesop;
    have h_path : ∃ l' : GridPath, IsValidPath (m, n) (m + 1, n) l' := by
      exact ⟨ [ ( ( m, n ), ( m + 1, n ) ) ], by exact IsValidPath.cons _ _ _ _ ( by exact Or.inl ⟨ rfl, rfl ⟩ ) ( by exact IsValidPath.nil _ ) ⟩;
    aesop;
    have h_path : ∃ l' : GridPath, IsValidPath (0, 0) (m + 1, n) l' := by
      have h_path : ∀ p q r : GridPoint, ∀ l : GridPath, IsValidPath p q l → ∀ w : GridPath, IsValidPath q r w → ∃ l' : GridPath, IsValidPath p r l' := by
        intros p q r l hl w hw;
        induction hl <;> aesop;
        exact ⟨ ( p_1, q_1 ) :: w_2, by exact IsValidPath.cons _ _ _ _ h_edge h_1 ⟩;
      exact h_path _ _ _ _ hl _ h;
    obtain ⟨ l', hl' ⟩ := h_path;
    replace h_empty := Finset.ext_iff.mp h_empty l'; aesop;
    exact h_empty <| by unfold paths; aesop;

/-
Definition of LPP value.
-/
/-- The Last Passage Percolation value for a given weight function. -/
noncomputable def LPP_value (m n : ℕ) (weights : Edge → ℝ) : ℝ :=
  ((paths m n).image (fun p => (p.map weights).sum)).max' (by simp [paths_nonempty])

/-
CDF of the N-approximate Gumbel distribution.
-/
noncomputable def f_approx_gumbel (N : ℝ) (x : ℝ) : ℝ :=
  if x > -Real.log N then (1 - Real.exp (-x) / N) ^ N else 0

/-
CDF of the Gumbel distribution.
-/
noncomputable def gumbel_cdf (x : ℝ) : ℝ := Real.exp (-Real.exp (-x))

/-
The coupling identity: g(y) = f_N(h_N(y) + y).
-/
theorem coupling_identity (N : ℝ) (hN : 1 ≤ N) (y : ℝ) :
    gumbel_cdf y = f_approx_gumbel N (h N y + y) := by
      unfold gumbel_cdf f_approx_gumbel h;
      rw [ Real.exp_neg, inv_eq_iff_eq_inv ] ; norm_num;
      rw [ if_pos ];
      · rw [ Real.exp_log ];
        · rw [ mul_div_cancel_left₀ _ ( by positivity ), sub_sub_cancel, ← Real.exp_mul ] ; ring;
          norm_num [ show N ≠ 0 by linarith ];
          rw [ ← Real.exp_neg, neg_neg ];
        · exact mul_pos ( by positivity ) ( sub_pos_of_lt ( Real.exp_lt_one_iff.mpr ( by ring_nf; norm_num; positivity ) ) );
      · exact Real.log_lt_log ( mul_pos ( by positivity ) ( sub_pos.mpr ( by rw [ Real.exp_lt_one_iff ] ; exact div_neg_of_neg_of_pos ( neg_lt_zero.mpr ( Real.exp_pos _ ) ) ( by positivity ) ) ) ) ( mul_lt_of_lt_one_right ( by positivity ) ( sub_lt_self _ ( by positivity ) ) )

/-
Definitions of T_Gumbel, T_Approx, and L_Exp.
-/
open MeasureTheory ProbabilityTheory

noncomputable def T_Gumbel (m n : ℕ) {Ω : Type*} (Y : Edge → Ω → ℝ) : Ω → ℝ :=
  fun ω => LPP_value m n (fun e => Y e ω)

noncomputable def T_Approx (m n : ℕ) (N : ℝ) {Ω : Type*} (Y : Edge → Ω → ℝ) : Ω → ℝ :=
  fun ω => LPP_value m n (fun e => h N (Y e ω) + Y e ω)

noncomputable def L_Exp (m n : ℕ) {Ω : Type*} (E : Edge → Ω → ℝ) : Ω → ℝ :=
  fun ω => LPP_value m n (fun e => E e ω)

/-
Constants C_g, sigma_g and the Tracy-Widom GUE distribution F_GUE.
-/
opaque C_g : ℝ
opaque sigma_g : ℝ
opaque F_GUE : ℝ → ℝ

/-
Checking the signature of iIndepFun.
-/
#check iIndepFun

/-
Definition of a grid of i.i.d. Gumbel random variables.
-/
def IsGumbelGrid {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) (Y : Edge → Ω → ℝ) : Prop :=
  iIndepFun Y μ ∧ ∀ e x, μ {ω | Y e ω ≤ x} = ENNReal.ofReal (gumbel_cdf x)

/-
Checking for MeasurableSpace instance on Real and borel definition.
-/
#synth MeasurableSpace ℝ
#check borel

/-
The scaled and centered LPP random variable.
-/
noncomputable def scaled_centered_LPP (n : ℕ) (N : ℝ) {Ω : Type*} (Y : Edge → Ω → ℝ) : Ω → ℝ :=
  fun ω => (T_Approx n n N Y ω - C_g * n) / (sigma_g * (n : ℝ) ^ (1/3 : ℝ))

/-
Definition of a grid of i.i.d. N-approximate Gumbel random variables.
-/
def IsApproxGumbelGrid {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) (N : ℝ) (Y : Edge → Ω → ℝ) : Prop :=
  iIndepFun Y μ ∧ ∀ e x, μ {ω | Y e ω ≤ x} = ENNReal.ofReal (f_approx_gumbel N x)

/-
The sequence of probabilities in the main theorem.
-/
noncomputable def prob_seq (α : ℝ) (r : ℝ)
  {Ω : ℕ → Type*} [∀ n, MeasurableSpace (Ω n)] (μ : ∀ n, Measure (Ω n)) (Y : ∀ n, Edge → Ω n → ℝ) (n : ℕ) : ℝ :=
  ((μ n) {ω | scaled_centered_LPP n (Nat.floor ((n : ℝ) ^ α)) (Y n) ω ≤ r}).toReal

/-
Upper bound on the difference between approximate and exact Gumbel LPP.
-/
theorem coupling_upper_bound (n : ℕ) (N : ℝ) (hN : 1 ≤ N) {Ω : Type*} (Y : Edge → Ω → ℝ) (ω : Ω) :
    T_Approx n n N Y ω - T_Gumbel n n Y ω ≤ (1 / N) * L_Exp n n (fun e ω => Real.exp (- (Y e ω))) ω := by
      norm_num [ T_Approx, T_Gumbel, L_Exp ];
      unfold LPP_value;
      rw [ Finset.max'_le_iff ];
      aesop;
      refine' add_le_add _ _;
      · refine' le_trans _ ( mul_le_mul_of_nonneg_left ( Finset.le_max' _ _ <| Finset.mem_image_of_mem _ left ) <| by positivity );
        -- By Lemma 1, we know that $h_N(x) \leq e^{-x}/N$ for all $x$.
        have h_le : ∀ x : ℝ, h N x ≤ Real.exp (-x) / N := by
          exact fun x => lemma_1 N hN |>.2.1 x |>.2;
        simpa [ div_eq_inv_mul, List.sum_map_mul_left ] using List.sum_le_sum fun x hx => h_le ( Y x ω );
      · exact Finset.le_max' ( Finset.image ( fun p => ( List.map ( fun e => Y e ω ) p ).sum ) ( paths n n ) ) _ ( Finset.mem_image_of_mem _ left )

/-
Lower bound on the difference between approximate and exact Gumbel LPP using Jensen's inequality.
-/
theorem coupling_lower_bound (n : ℕ) (N : ℝ) (hN : 1 ≤ N) {Ω : Type*} (Y : Edge → Ω → ℝ) (ω : Ω) :
    2 * n * h N (T_Gumbel n n Y ω / (2 * n)) ≤ T_Approx n n N Y ω - T_Gumbel n n Y ω := by
      rcases eq_or_ne n 0 with ( rfl | hn ) <;> norm_num at *;
      · unfold T_Gumbel T_Approx;
        unfold LPP_value; aesop;
        refine' le_trans _ ( Finset.le_max' _ _ <| Finset.mem_image_of_mem _ a_1 ) ; aesop;
        -- Since $h_N(x)$ is non-negative for all $x$, the sum of $h_N(Y_i \omega)$ over any path is also non-negative.
        have h_nonneg : ∀ x : ℝ, 0 ≤ h N x := by
          exact fun x => by have := lemma_1 N hN; exact this.2.1 x |>.1.le;
        exact List.sum_nonneg ( by aesop );
      · -- Let's denote the geodesic (maximizing path) for $T_{Gumbel}$ as $\pi^*$.
        obtain ⟨pi_star, h_pi_star⟩ : ∃ pi_star : GridPath, IsValidPath (0, 0) (n, n) pi_star ∧ (pi_star.map (fun e => Y e ω)).sum = T_Gumbel n n Y ω := by
          have h_exists_pi_star : ∃ pi_star ∈ paths n n, (pi_star.map (fun e => Y e ω)).sum = T_Gumbel n n Y ω := by
            have := Finset.max'_mem ( Finset.image ( fun p : GridPath => ( p.map ( fun e => Y e ω ) ).sum ) ( paths n n ) ) ⟨ _, Finset.mem_image_of_mem _ ( Classical.choose_spec ( paths_nonempty n n ) ) ⟩ ; aesop;
          unfold paths at h_exists_pi_star; aesop;
        -- By Jensen's inequality and convexity of $h_N$, we have $\frac{1}{2n} \sum_{e \in \pi^*} h_N(Y_e) \ge h_N(\frac{1}{2n} \sum_{e \in \pi^*} Y_e)$.
        have h_jensen : (pi_star.map (fun e => h N (Y e ω))).sum ≥ 2 * n * h N ((pi_star.map (fun e => Y e ω)).sum / (2 * n)) := by
          -- Since $\pi^*$ is a valid path from $(0,0)$ to $(n,n)$, it has length $2n$.
          have h_pi_star_length : (pi_star.length : ℝ) = 2 * n := by
            have h_pi_star_length : ∀ {p q : GridPoint} {l : GridPath}, IsValidPath p q l → (l.length : ℝ) = q.1 + q.2 - p.1 - p.2 := by
              intros p q l hl; induction hl <;> aesop;
              cases h_edge <;> aesop <;> linarith;
            exact h_pi_star_length h_pi_star.1 ▸ by push_cast; ring;
          have h_jensen : ∀ (f : ℝ → ℝ), ConvexOn ℝ (Set.univ : Set ℝ) f → ∀ (x : List ℝ), x.length = 2 * n → (List.map f x).sum ≥ 2 * n * f ((List.sum x) / (2 * n)) := by
            intros f hf x hx_length
            have h_jensen : (∑ i ∈ Finset.range (2 * n), f (x.get! i)) ≥ 2 * n * f ((∑ i ∈ Finset.range (2 * n), x.get! i) / (2 * n)) := by
              have h_jensen : (∑ i ∈ Finset.range (2 * n), (1 / (2 * n)) * f (x.get! i)) ≥ f ((∑ i ∈ Finset.range (2 * n), (1 / (2 * n)) * x.get! i)) := by
                apply ConvexOn.map_sum_le hf;
                · exact fun _ _ => by positivity;
                · simp +decide [ hn ];
                  ring_nf; norm_num [ hn ];
                · exact fun _ _ => Set.mem_univ _;
              simp_all +decide [ div_eq_inv_mul, ← Finset.mul_sum _ _ _ ];
              convert mul_le_mul_of_nonneg_left h_jensen ( show ( 0 : ℝ ) ≤ 2 * n by positivity ) using 1 ; ring_nf ; norm_num [ hn ];
            convert h_jensen using 1;
            · rw [ ← hx_length, Finset.sum_range ];
              simp +decide [ List.sum_eq_foldr, Finset.sum_range, List.get! ];
            · norm_num [ ← hx_length, Finset.sum_range, List.get! ];
          convert h_jensen ( fun x => h N x ) ( lemma_1 N hN |>.1 ) ( List.map ( fun e => Y e ω ) pi_star ) _ using 1;
          · rw [ List.map_map ];
            rfl;
          · simpa using mod_cast h_pi_star_length;
        -- Since $\pi^*$ is a valid path, we have $T_{Approx} \ge S_B(\pi^*) + T_{Gumbel}$.
        have h_approx_ge : T_Approx n n N Y ω ≥ (pi_star.map (fun e => h N (Y e ω) + Y e ω)).sum := by
          refine' Finset.le_max' _ _ _;
          unfold paths; aesop;
        simp_all +decide [ List.sum_map_add ];
        linarith

/-
Definitions of the properties representing known results from the paper.
-/
open Filter Topology MeasureTheory ProbabilityTheory

def ExactGumbelConvergenceProperty : Prop :=
  ∀ (r : ℝ),
  ∀ {Ω : ℕ → Type*} [∀ n, MeasurableSpace (Ω n)] (μ : ∀ n, Measure (Ω n)) (Y : ∀ n, Edge → Ω n → ℝ),
  (∀ n, IsGumbelGrid (μ n) (Y n)) →
  Tendsto (fun n => ((μ n) {ω | (T_Gumbel n n (Y n) ω - C_g * n) / (sigma_g * (n : ℝ) ^ (1/3 : ℝ)) ≤ r}).toReal) atTop (𝓝 (F_GUE r))

def TimeConstantGumbelProperty : Prop :=
  ∃ D_ell > 0, ∀ {Ω : ℕ → Type*} [∀ n, MeasurableSpace (Ω n)] (μ : ∀ n, Measure (Ω n)) (Y : ∀ n, Edge → Ω n → ℝ),
  (∀ n, IsGumbelGrid (μ n) (Y n)) →
  ∀ ε > 0, Tendsto (fun n => ((μ n) {ω | |T_Gumbel n n (Y n) ω / n - D_ell| > ε}).toReal) atTop (𝓝 0)

def TimeConstantExpProperty : Prop :=
  ∃ D_L > 0, ∀ {Ω : ℕ → Type*} [∀ n, MeasurableSpace (Ω n)] (μ : ∀ n, Measure (Ω n)) (E : ∀ n, Edge → Ω n → ℝ),
  (∀ n, iIndepFun (E n) (μ n) ∧ ∀ e x, (μ n) {ω | E n e ω ≤ x} = ENNReal.ofReal (if 0 ≤ x then 1 - Real.exp (-x) else 0)) →
  ∀ ε > 0, Tendsto (fun n => ((μ n) {ω | |L_Exp n n (E n) ω / n - D_L| > ε}).toReal) atTop (𝓝 0)

/-
Definition of convergence in probability to 0.
-/
/-- Convergence in probability to 0. -/
def ConvergesInProbZero {Ω : ℕ → Type*} [∀ n, MeasurableSpace (Ω n)] (μ : ∀ n, Measure (Ω n)) (Y : ∀ n, Ω n → ℝ) : Prop :=
  ∀ ε > 0, Tendsto (fun n => ((μ n) {ω | |Y n ω| > ε}).toReal) atTop (𝓝 0)

/-
Upper bound inequality for Slutsky's theorem.
-/
theorem slutsky_upper_bound {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω)
    (X Y : Ω → ℝ) (r ε : ℝ) :
    μ {ω | X ω + Y ω ≤ r} ≤ μ {ω | X ω ≤ r + ε} + μ {ω | |Y ω| > ε} := by
      refine' le_trans ( MeasureTheory.measure_mono _ ) ( MeasureTheory.measure_union_le _ _ );
      intro ω hω; contrapose! hω; aesop; cases abs_cases ( Y ω ) <;> linarith;

/-
Lower bound inequality for Slutsky's theorem.
-/
theorem slutsky_lower_bound {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω)
    (X Y : Ω → ℝ) (r ε : ℝ) :
    μ {ω | X ω ≤ r - ε} ≤ μ {ω | X ω + Y ω ≤ r} + μ {ω | |Y ω| > ε} := by
      refine' le_trans _ ( MeasureTheory.measure_union_le _ _ );
      refine' MeasureTheory.measure_mono fun ω hω => _;
      norm_num +zetaDelta at *;
      contrapose! hω; cases abs_cases ( Y ω ) <;> linarith;

/-
If $a_n \le b_n + c_n$, $b_n \to B$, and $c_n \to 0$, then eventually $a_n \le B + \epsilon$.
-/
lemma limit_upper_bound_helper (a b c : ℕ → ℝ) (B : ℝ)
    (hb : Tendsto b atTop (𝓝 B))
    (hc : Tendsto c atTop (𝓝 0))
    (h_le : ∀ n, a n ≤ b n + c n) :
    ∀ ε > 0, ∀ᶠ n in atTop, a n ≤ B + ε := by
      intro ε hε; filter_upwards [ hb.eventually ( Metric.ball_mem_nhds B <| half_pos hε ), hc.eventually ( Metric.ball_mem_nhds _ <| half_pos hε ) ] with n hn hn' using by linarith [ h_le n, abs_lt.mp <| Metric.mem_ball.mp hn, abs_lt.mp <| Metric.mem_ball.mp hn' ] ;

/-
Upper bound direction for Slutsky's theorem.
-/
theorem slutsky_cdf_upper {Ω : ℕ → Type*} [∀ n, MeasurableSpace (Ω n)] (μ : ∀ n, Measure (Ω n)) [∀ n, IsProbabilityMeasure (μ n)]
    (X Y : ∀ n, Ω n → ℝ) (F : ℝ → ℝ)
    (h_cont : Continuous F)
    (h_X : ∀ r, Tendsto (fun n => ((μ n) {ω | X n ω ≤ r}).toReal) atTop (𝓝 (F r)))
    (h_Y : ConvergesInProbZero μ Y)
    (r : ℝ) :
    ∀ ε > 0, ∀ᶠ n in atTop, ((μ n) {ω | X n ω + Y n ω ≤ r}).toReal ≤ F r + ε := by
      -- For any $\epsilon > 0$, choose $\delta > 0$ such that $F(r + \delta) < F(r) + \epsilon / 2$.
      intro ε hε_pos
      obtain ⟨δ, hδ_pos, hδ⟩ : ∃ δ > 0, F (r + δ) < F r + ε / 2 := by
        have := Metric.continuous_iff.mp h_cont r ( ε / 2 ) ( half_pos hε_pos ) ; aesop;
        exact ⟨ w / 2, half_pos left, by linarith [ abs_lt.mp ( right ( r + w / 2 ) ( abs_lt.mpr ⟨ by linarith, by linarith ⟩ ) ) ] ⟩;
      -- By `slutsky_upper_bound` with $\delta$, we have $\mu(\dots) \le \mu(\dots) + \mu(\dots)$ in ENNReal.
      have h_upper_bound : ∀ n, ((μ n) {ω | X n ω + Y n ω ≤ r}).toReal ≤ ((μ n) {ω | X n ω ≤ r + δ}).toReal + ((μ n) {ω | |Y n ω| > δ}).toReal := by
        intro n;
        convert ENNReal.toReal_mono _ ( slutsky_upper_bound ( μ n ) ( X n ) ( Y n ) r δ ) using 1;
        · rw [ ENNReal.toReal_add ] <;> norm_num;
        · exact ne_of_lt ( ENNReal.add_lt_top.mpr ⟨ MeasureTheory.measure_lt_top _ _, MeasureTheory.measure_lt_top _ _ ⟩ );
      have := h_X ( r + δ );
      filter_upwards [ this.eventually ( gt_mem_nhds <| show F ( r + δ ) < F r + ε / 2 by linarith ), h_Y δ hδ_pos |> fun h => h.eventually ( gt_mem_nhds <| show ( 0 : ℝ ) < ε / 2 by linarith ) ] with n hn hn' using by linarith [ h_upper_bound n ] ;

/-
Real-valued version of Slutsky upper bound inequality.
-/
theorem slutsky_upper_bound_real {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) [IsFiniteMeasure μ]
    (X Y : Ω → ℝ) (r ε : ℝ) :
    (μ {ω | X ω + Y ω ≤ r}).toReal ≤ (μ {ω | X ω ≤ r + ε}).toReal + (μ {ω | |Y ω| > ε}).toReal := by
      have := @slutsky_upper_bound Ω _ μ X Y r ε ; aesop;
      convert ENNReal.toReal_mono _ this using 1 <;> norm_num [ ENNReal.toReal_add ]

/-
If $a_n \ge b_n - c_n$, $b_n \to B$, and $c_n \to 0$, then eventually $a_n \ge B - \epsilon$.
-/
lemma limit_lower_bound_helper (a b c : ℕ → ℝ) (B : ℝ)
    (hb : Tendsto b atTop (𝓝 B))
    (hc : Tendsto c atTop (𝓝 0))
    (h_ge : ∀ n, a n ≥ b n - c n) :
    ∀ ε > 0, ∀ᶠ n in atTop, a n ≥ B - ε := by
      intro ε hε;
      filter_upwards [ hb.eventually ( Metric.ball_mem_nhds _ ( half_pos hε ) ), hc.eventually ( Metric.ball_mem_nhds _ ( half_pos hε ) ) ] with n hn hb using by linarith [ abs_lt.mp hn, abs_lt.mp hb, h_ge n ] ;

/-
Lower bound direction for Slutsky's theorem.
-/
theorem slutsky_cdf_lower {Ω : ℕ → Type*} [∀ n, MeasurableSpace (Ω n)] (μ : ∀ n, Measure (Ω n)) [∀ n, IsProbabilityMeasure (μ n)]
    (X Y : ∀ n, Ω n → ℝ) (F : ℝ → ℝ)
    (h_cont : Continuous F)
    (h_X : ∀ r, Tendsto (fun n => ((μ n) {ω | X n ω ≤ r}).toReal) atTop (𝓝 (F r)))
    (h_Y : ConvergesInProbZero μ Y)
    (r : ℝ) :
    ∀ ε > 0, ∀ᶠ n in atTop, ((μ n) {ω | X n ω + Y n ω ≤ r}).toReal ≥ F r - ε := by
      aesop;
      -- Fix $\delta > 0$ such that $F(r - \delta) > F(r) - \frac{\epsilon}{2}$.
      obtain ⟨δ, hδ_pos, hδ⟩ : ∃ δ > 0, F r - ε / 2 < F (r - δ) := by
        have := Metric.continuous_iff.1 h_cont ( r ) ( ε / 2 ) ( half_pos a ) ; aesop;
        exact ⟨ w / 2, half_pos left, by linarith [ abs_lt.mp ( right ( r - w / 2 ) ( abs_lt.mpr ⟨ by linarith, by linarith ⟩ ) ) ] ⟩;
      -- By `slutsky_lower_bound` with $\delta$, we have $b_n \le a_n + c_n$, so $a_n \ge b_n - c_n$.
      have h_lower_bound : ∀ n, (((μ n) {ω | (X n ω) ≤ r - δ}).toReal) ≤ (((μ n) {ω | (X n ω) + (Y n ω) ≤ r}).toReal) + (((μ n) {ω | |(Y n ω)| > δ}).toReal) := by
        have h_lower_bound : ∀ n, (μ n) {ω | (X n ω) ≤ r - δ} ≤ (μ n) {ω | (X n ω) + (Y n ω) ≤ r} + (μ n) {ω | |(Y n ω)| > δ} := by
          exact?;
        intro n; specialize h_lower_bound n; rw [ ← ENNReal.toReal_add ] ; aesop;
        · exact MeasureTheory.measure_ne_top _ _;
        · exact MeasureTheory.measure_ne_top _ _;
      -- We have $b_n \to F(r - \delta)$ (by `h_X`) and $c_n \to 0$ (by `h_Y`).
      have h_b_c : Filter.Tendsto (fun n => (((μ n) {ω | (X n ω) ≤ r - δ}).toReal)) Filter.atTop (𝓝 (F (r - δ))) ∧ Filter.Tendsto (fun n => (((μ n) {ω | |(Y n ω)| > δ}).toReal)) Filter.atTop (𝓝 0) := by
        exact ⟨ h_X _, by simpa using h_Y δ hδ_pos ⟩;
      rcases Metric.tendsto_atTop.mp h_b_c.1 ( ε / 4 ) ( by linarith ) with ⟨ N₁, hN₁ ⟩ ; rcases Metric.tendsto_atTop.mp h_b_c.2 ( ε / 4 ) ( by linarith ) with ⟨ N₂, hN₂ ⟩ ; exact ⟨ Max.max N₁ N₂, fun n hn => by linarith [ abs_lt.mp ( hN₁ n ( le_trans ( le_max_left _ _ ) hn ) ), abs_lt.mp ( hN₂ n ( le_trans ( le_max_right _ _ ) hn ) ), h_lower_bound n ] ⟩

/-
Slutsky's theorem for CDFs.
-/
theorem slutsky_cdf {Ω : ℕ → Type*} [∀ n, MeasurableSpace (Ω n)] (μ : ∀ n, Measure (Ω n)) [∀ n, IsProbabilityMeasure (μ n)]
    (X Y : ∀ n, Ω n → ℝ) (F : ℝ → ℝ)
    (h_cont : Continuous F)
    (h_X : ∀ r, Tendsto (fun n => ((μ n) {ω | X n ω ≤ r}).toReal) atTop (𝓝 (F r)))
    (h_Y : ConvergesInProbZero μ Y) :
    ∀ r, Tendsto (fun n => ((μ n) {ω | X n ω + Y n ω ≤ r}).toReal) atTop (𝓝 (F r)) := by
      intro r
      have h_upper : ∀ ε > 0, ∀ᶠ n in atTop, ((μ n) {ω | X n ω + Y n ω ≤ r}).toReal ≤ F r + ε := by
        exact?
      have h_lower : ∀ ε > 0, ∀ᶠ n in atTop, ((μ n) {ω | X n ω + Y n ω ≤ r}).toReal ≥ F r - ε := by
        exact?
      exact (by
      rw [ Metric.tendsto_nhds ];
      exact fun ε εpos => by filter_upwards [ h_upper ( ε / 2 ) ( half_pos εpos ), h_lower ( ε / 2 ) ( half_pos εpos ) ] with n hn₁ hn₂ using abs_lt.mpr ⟨ by linarith, by linarith ⟩ ;)

/-
Definition of convergence in probability to a constant.
-/
/-- Convergence in probability to a constant. -/
def ConvergesInProbConst {Ω : ℕ → Type*} [∀ n, MeasurableSpace (Ω n)] (μ : ∀ n, Measure (Ω n)) (Y : ∀ n, Ω n → ℝ) (c : ℝ) : Prop :=
  ∀ ε > 0, Tendsto (fun n => ((μ n) {ω | |Y n ω - c| > ε}).toReal) atTop (𝓝 0)

/-
If $|y| > |c| + 1$, then $|y - c| > 1$.
-/
lemma abs_gt_of_abs_sub_gt (y c : ℝ) : |y| > |c| + 1 → |y - c| > 1 := by
  cases abs_cases ( y - c ) <;> cases abs_cases y <;> cases abs_cases c <;> intros <;> linarith

/-
If $Y_n \to c$ in probability, then $P(|Y_n| > |c| + 1) \to 0$.
-/
lemma converges_in_prob_bounded {Ω : ℕ → Type*} [∀ n, MeasurableSpace (Ω n)] (μ : ∀ n, Measure (Ω n)) [∀ n, IsFiniteMeasure (μ n)]
    (Y : ∀ n, Ω n → ℝ) (c : ℝ)
    (h : ConvergesInProbConst μ Y c) :
    Tendsto (fun n => ((μ n) {ω | |Y n ω| > |c| + 1}).toReal) atTop (𝓝 0) := by
      have h_bound : ∀ n, ((μ n) {ω | |Y n ω| > |c| + 1}).toReal ≤ ((μ n) {ω | |Y n ω - c| > 1}).toReal := by
        intro n; apply_rules [ ENNReal.toReal_mono, MeasureTheory.measure_mono ] ; aesop;
        exact fun ω hω => by norm_num at *; cases abs_cases ( Y n ω ) <;> cases abs_cases c <;> cases abs_cases ( Y n ω - c ) <;> linarith;
      exact squeeze_zero ( fun n => ENNReal.toReal_nonneg ) h_bound ( by simpa using h 1 zero_lt_one )

/-
Product of a sequence converging in probability to a constant and a sequence converging to 0 converges in probability to 0.
-/
lemma converges_in_prob_mul_zero {Ω : ℕ → Type*} [∀ n, MeasurableSpace (Ω n)] (μ : ∀ n, Measure (Ω n)) [∀ n, IsFiniteMeasure (μ n)]
    (Y : ∀ n, Ω n → ℝ) (c : ℝ) (a : ℕ → ℝ)
    (h_Y : ConvergesInProbConst μ Y c)
    (h_a : Tendsto a atTop (𝓝 0)) :
    ConvergesInProbZero μ (fun n ω => a n * Y n ω) := by
      intro ε hε;
      -- Fix $\epsilon > 0$. Since $a_n \to 0$, there exists $N$ such that for all $n \ge N$, $|a_n| < \frac{\epsilon}{|c| + 1}$.
      obtain ⟨N, hN⟩ : ∃ N, ∀ n ≥ N, |a n| < ε / (|c| + 1) := by
        simpa using h_a.eventually ( Metric.ball_mem_nhds _ <| by positivity );
      -- For such $n$, if $|Y_n| \le |c| + 1$, then $|a_n Y_n| < \frac{\epsilon}{|c| + 1} (|c| + 1) = \epsilon$.
      have h_bound : ∀ n ≥ N, {ω | ε < |a n * Y n ω|} ⊆ {ω | |Y n ω| > |c| + 1} := by
        intro n hn ω hω; specialize hN n hn; rw [ lt_div_iff₀ ( by positivity ) ] at hN; contrapose! hω; aesop;
        exact le_trans ( mul_le_mul_of_nonneg_left hω ( abs_nonneg _ ) ) hN.le;
      -- Thus, for $n \ge N$, $\mu(\{|a_n Y_n| > \epsilon\}) \le \mu(\{|Y_n| > |c| + 1\})$.
      have h_measure_bound : ∀ n ≥ N, ((μ n) {ω | ε < |a n * Y n ω|}).toReal ≤ ((μ n) {ω | |Y n ω| > |c| + 1}).toReal := by
        exact fun n hn => ENNReal.toReal_mono ( MeasureTheory.measure_ne_top _ _ ) ( MeasureTheory.measure_mono ( h_bound n hn ) );
      exact squeeze_zero_norm' ( Filter.eventually_atTop.mpr ⟨ N, fun n hn => by rw [ Real.norm_of_nonneg ( by positivity ) ] ; exact h_measure_bound n hn ⟩ ) ( converges_in_prob_bounded μ Y c h_Y )

/-
If $0 \le X \le Z$, then $P(|X| > \epsilon) \le P(|Z| > \epsilon)$.
-/
lemma squeeze_measure_le {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω)
    (X Z : Ω → ℝ) (ε : ℝ)
    (h_nonneg : ∀ ω, 0 ≤ X ω)
    (h_le : ∀ ω, X ω ≤ Z ω) :
    μ {ω | |X ω| > ε} ≤ μ {ω | |Z ω| > ε} := by
      apply_rules [ MeasureTheory.measure_mono ];
      aesop;
      cases abs_cases ( X a ) <;> cases abs_cases ( Z a ) <;> linarith [ h_nonneg a, h_le a ]

/-
The deterministic factor in the error term converges to 0.
-/
lemma deterministic_factor_limit (α : ℝ) (h_alpha : α > 2/3) :
    Tendsto (fun n => (n : ℝ) / (Nat.floor ((n : ℝ) ^ α) * (n : ℝ) ^ (1/3 : ℝ))) atTop (𝓝 0) := by
      -- We can factor out $n^{1/3}$ from the denominator and use the fact that $⌊n^\alpha⌋₊$ is approximately $n^\alpha$ for large $n$.
      have h_factor : Tendsto (fun n => (n : ℝ) ^ (1 - α - 1 / 3 : ℝ)) Filter.atTop (nhds 0) := by
        simpa using tendsto_rpow_neg_atTop ( by linarith : 0 < - ( 1 - α - 1 / 3 ) );
      -- Using the fact that $⌊n^\alpha⌋₊$ is approximately $n^\alpha$ for large $n$, we can bound the expression.
      have h_bound : ∀ᶠ n in Filter.atTop, (n : ℝ) / (⌊n ^ α⌋₊ * n ^ (1 / 3 : ℝ)) ≤ 2 * (n : ℝ) ^ (1 - α - 1 / 3 : ℝ) := by
        -- Using the fact that $⌊n^\alpha⌋₊$ is approximately $n^\alpha$ for large $n$, we can bound the expression as follows:
        have h_bound : ∀ᶠ n in Filter.atTop, (n : ℝ) / (⌊n ^ α⌋₊ * n ^ (1 / 3 : ℝ)) ≤ (n : ℝ) / ((n ^ α / 2) * n ^ (1 / 3 : ℝ)) := by
          filter_upwards [ Filter.eventually_gt_atTop 1, Filter.eventually_gt_atTop ( 2 ^ ( 1 / α ) ) ] with n hn hn';
          gcongr;
          linarith [ Nat.lt_floor_add_one ( n ^ α ), show ( n : ℝ ) ^ α ≥ 2 by exact le_trans ( by exact le_of_eq ( by rw [ ← Real.rpow_mul ( by positivity ), one_div_mul_cancel ( by positivity ), Real.rpow_one ] ) ) ( Real.rpow_le_rpow ( by positivity ) hn'.le ( by positivity ) ) ];
        filter_upwards [ h_bound, Filter.eventually_gt_atTop 0 ] with n hn hn' ; convert hn using 1 ; ring;
        rw [ show ( 2 / 3 - α : ℝ ) = 1 - α - 1 / 3 by ring, Real.rpow_sub hn', Real.rpow_sub hn' ] ; norm_num ; ring;
      refine' squeeze_zero_norm' _ _;
      exacts [ fun n => 2 * n ^ ( 1 - α - 1 / 3 ), by filter_upwards [ h_bound, Filter.eventually_gt_atTop 0 ] with n hn hn' using by rw [ Real.norm_of_nonneg ( by positivity ) ] ; exact hn, by simpa using h_factor.const_mul 2 ]

/-
The difference between the approximate and exact LPP is non-negative and bounded by the exponential LPP scaled by 1/N.
-/
lemma coupling_ineq_lift (n : ℕ) (N : ℝ) (hN : 1 ≤ N) {Ω : Type*} (Y : Edge → Ω → ℝ) (ω : Ω) :
    0 ≤ T_Approx n n N Y ω - T_Gumbel n n Y ω ∧
    T_Approx n n N Y ω - T_Gumbel n n Y ω ≤ (1 / N) * L_Exp n n (fun e ω => Real.exp (- (Y e ω))) ω := by
      refine' ⟨ _, _ ⟩;
      · refine' le_trans _ ( coupling_lower_bound n N hN Y ω );
        exact mul_nonneg ( by positivity ) ( lemma_1 N hN |>.2.1 _ |>.1.le );
      · exact?

/-
Calculation of the transformed CDF for positive y.
-/
lemma gumbel_exp_neg_cdf_calc (y : ℝ) (hy : 0 < y) :
    1 - gumbel_cdf (-Real.log y) = 1 - Real.exp (-y) := by
      unfold gumbel_cdf; norm_num [ Real.exp_neg, Real.exp_log hy ] ;

/-
The Gumbel CDF is continuous.
-/
lemma gumbel_cdf_continuous : Continuous gumbel_cdf := by
  exact Real.continuous_exp.comp <| Continuous.neg <| Real.continuous_exp.comp <| Continuous.neg continuous_id

/-
Set difference characterization of the interval (a, b].
-/
lemma set_Ioc_eq_diff {Ω : Type*} (Y : Ω → ℝ) (a b : ℝ) :
    {ω | a < Y ω ∧ Y ω ≤ b} = {ω | Y ω ≤ b} \ {ω | Y ω ≤ a} := by
      ext ω; aesop

/-
The CDF function F is monotone non-decreasing.
-/
lemma cdf_mono {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) (Y : Ω → ℝ) (F : ℝ → ℝ)
    (h_cdf : ∀ x, μ {ω | Y ω ≤ x} = ENNReal.ofReal (F x))
    (hF_nonneg : ∀ x, 0 ≤ F x) :
    Monotone F := by
      -- By definition of F, we know that μ {ω | Y ω ≤ x} = ENNReal.ofReal (F x) and μ {ω | Y ω ≤ y} = ENNReal.ofReal (F y).
      have h_monotone : ∀ x y, x ≤ y → μ {ω | Y ω ≤ x} ≤ μ {ω | Y ω ≤ y} := by
        exact fun x y hxy => MeasureTheory.measure_mono fun ω hω => le_trans hω.out hxy;
      aesop

/-
The measure of an interval (a, b] is F(b) - F(a), assuming Y is measurable.
-/
lemma measure_Ioc_eq_cdf_sub {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) (Y : Ω → ℝ) (F : ℝ → ℝ)
    (h_meas : Measurable Y)
    (h_cdf : ∀ x, μ {ω | Y ω ≤ x} = ENNReal.ofReal (F x))
    (hF_nonneg : ∀ x, 0 ≤ F x)
    (a b : ℝ) (hab : a < b) :
    μ {ω | a < Y ω ∧ Y ω ≤ b} = ENNReal.ofReal (F b - F a) := by
      rw [ show { ω | a < Y ω ∧ Y ω ≤ b } = { ω | Y ω ≤ b } \ { ω | Y ω ≤ a } by ext; aesop, MeasureTheory.measure_diff ] <;> norm_num [ h_cdf ];
      · rw [ ENNReal.ofReal_sub ] ; aesop;
      · exact fun ω hω => le_trans hω hab.le;
      · exact measurableSet_le h_meas measurable_const |> MeasurableSet.nullMeasurableSet

/-
The measure of (a, b] is the difference of the measures of (-inf, b] and (-inf, a].
-/
lemma measure_Ioc_eq_measure_le_sub_measure_le {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) (Y : Ω → ℝ)
    (h_meas : Measurable Y)
    (a b : ℝ) (hab : a < b)
    (h_finite : μ {ω | Y ω ≤ a} ≠ ⊤) :
    μ {ω | a < Y ω ∧ Y ω ≤ b} = μ {ω | Y ω ≤ b} - μ {ω | Y ω ≤ a} := by
      rw [ ← MeasureTheory.measure_diff ];
      · exact congr_arg _ ( by ext; aesop );
      · exact fun x hx => le_trans hx.out hab.le;
      · exact h_meas.nullMeasurable measurableSet_Iic;
      · assumption

/-
If a random variable has a continuous CDF at y, the probability it equals y is 0.
-/
lemma measure_singleton_eq_zero_of_continuous_cdf {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) (Y : Ω → ℝ) (F : ℝ → ℝ)
    (h_meas : Measurable Y)
    (y : ℝ)
    (h_cdf : ∀ x, μ {ω | Y ω ≤ x} = ENNReal.ofReal (F x))
    (hF_nonneg : ∀ x, 0 ≤ F x)
    (h_cont : ContinuousAt F y) :
    μ {ω | Y ω = y} = 0 := by
      -- By the squeeze theorem, since $\mu(y - 1/(n+1) < Y \le y)$ tends to $0$ as $n$ tends to infinity, we have $\mu(Y = y) \le 0$.
      have h_squeeze : Filter.Tendsto (fun n : ℕ => μ {ω | y - 1 / (n + 1) < Y ω ∧ Y ω ≤ y}) Filter.atTop (nhds 0) := by
        -- By the properties of the CDF, we have $\mu(y - 1/(n+1) < Y \le y) = ENNReal.ofReal (F(y) - F(y - 1/(n+1)))$.
        have h_cdf_interval : ∀ n : ℕ, μ {ω | y - 1 / (n + 1) < Y ω ∧ Y ω ≤ y} = ENNReal.ofReal (F y - F (y - 1 / (n + 1))) := by
          intro n;
          convert measure_Ioc_eq_cdf_sub μ Y F h_meas h_cdf hF_nonneg ( y - 1 / ( n + 1 ) ) y ( sub_lt_self _ ( by positivity ) ) using 1;
        aesop;
        simpa using ENNReal.tendsto_ofReal ( Filter.Tendsto.const_sub ( F y ) ( h_cont.tendsto.comp ( show Filter.Tendsto ( fun n : ℕ => y - ( n + 1 : ℝ ) ⁻¹ ) Filter.atTop ( nhds y ) by exact le_trans ( tendsto_const_nhds.sub ( tendsto_inv_atTop_zero.comp ( Filter.tendsto_atTop_add_const_right _ _ tendsto_natCast_atTop_atTop ) ) ) ( by simp +decide ) ) ) );
      aesop;
      exact le_antisymm ( le_of_tendsto_of_tendsto' tendsto_const_nhds h_squeeze fun n => by exact MeasureTheory.measure_mono <| fun ω hω => ⟨ by linarith [ hω.symm, inv_pos.mpr ( by linarith : 0 < ( n : ℝ ) + 1 ) ], by linarith [ hω.symm, inv_pos.mpr ( by linarith : 0 < ( n : ℝ ) + 1 ) ] ⟩ ) bot_le

/-
The difference F(y) - F(y - 1/(n+1)) tends to 0 if F is continuous at y.
-/
lemma cdf_diff_tendsto_zero (F : ℝ → ℝ) (y : ℝ) (h_cont : ContinuousAt F y) :
    Tendsto (fun n : ℕ => F y - F (y - 1 / (n + 1))) atTop (nhds 0) := by
      simpa using h_cont.tendsto.comp ( show Filter.Tendsto ( fun n : ℕ => y - ( n + 1 : ℝ ) ⁻¹ ) Filter.atTop ( nhds y ) by simpa using tendsto_const_nhds.sub ( tendsto_one_div_add_atTop_nhds_zero_nat ) ) |> fun h => h.const_sub ( F y )

/-
The measure of a singleton for a Gumbel variable is 0.
-/
lemma gumbel_measure_singleton_zero {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) (Y : Ω → ℝ)
    (h_meas : Measurable Y)
    (hY : ∀ x, μ {ω | Y ω ≤ x} = ENNReal.ofReal (gumbel_cdf x)) (y : ℝ) :
    μ {ω | Y ω = y} = 0 := by
      -- Apply the lemma that states if a random variable has a continuous CDF at y, then the probability it equals y is 0.
      apply measure_singleton_eq_zero_of_continuous_cdf μ Y (fun x => gumbel_cdf x) h_meas y hY (fun x => by
        exact Real.exp_nonneg _) (by
      exact gumbel_cdf_continuous.continuousAt)

/-
The probability that a Gumbel variable is at least y is 1 - F(y).
-/
lemma gumbel_prob_ge {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) [IsProbabilityMeasure μ] (Y : Ω → ℝ)
    (h_meas : Measurable Y)
    (hY : ∀ x, μ {ω | Y ω ≤ x} = ENNReal.ofReal (gumbel_cdf x)) (y : ℝ) :
    μ {ω | Y ω ≥ y} = ENNReal.ofReal (1 - gumbel_cdf y) := by
      -- Since $Y$ is measurable, the set ${ω | y ≤ Y ω}$ is the complement of ${ω | Y ω ≤ y}$.
      have h_compl : μ {ω | y ≤ Y ω} = μ Set.univ - μ {ω | Y ω ≤ y} := by
        rw [ ← MeasureTheory.measure_diff ] <;> norm_num;
        · rw [ ← MeasureTheory.measure_congr ];
          rw [ MeasureTheory.ae_eq_set ] ; aesop;
          · exact MeasureTheory.measure_mono_null ( fun ω => by aesop ; linarith ) ( MeasureTheory.measure_empty );
          · rw [ show { ω | y ≤ Y ω } \ ( Set.univ \ { ω | Y ω ≤ y } ) = { ω | y ≤ Y ω ∧ y ≤ Y ω } ∩ { ω | Y ω ≤ y } by ext; aesop ] ; exact MeasureTheory.measure_mono_null ( fun x => by aesop ; linarith ) ( gumbel_measure_singleton_zero μ Y h_meas hY y );
        · exact h_meas.nullMeasurable measurableSet_Iic;
      rw [ ENNReal.ofReal_sub ] <;> aesop;
      exact Real.exp_nonneg _

/-
Transformation of Gumbel CDF to Exponential CDF.
-/
lemma gumbel_to_exp_cdf {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) [IsProbabilityMeasure μ] (Y : Ω → ℝ)
    (h_meas : Measurable Y)
    (hY : ∀ x, μ {ω | Y ω ≤ x} = ENNReal.ofReal (gumbel_cdf x)) :
    ∀ x, μ {ω | Real.exp (-Y ω) ≤ x} = ENNReal.ofReal (if 0 ≤ x then 1 - Real.exp (-x) else 0) := by
      aesop;
      · by_cases hx : x = 0;
        · simp +decide [ hx, Real.exp_ne_zero ];
          exact MeasureTheory.measure_mono_null ( fun ω hω => by linarith [ Real.exp_pos ( -Y ω ), hω.out ] ) ( MeasureTheory.measure_empty );
        · convert gumbel_prob_ge μ Y h_meas hY ( -Real.log x ) using 1;
          · congr with ω ; aesop;
            · linarith [ Real.log_exp ( -Y ω ), Real.log_le_log ( by positivity ) a ];
            · rw [ ← Real.log_le_log_iff ( by positivity ) ( by positivity ), Real.log_exp ] ; linarith;
          · unfold gumbel_cdf; norm_num [ Real.exp_neg, Real.exp_log ( lt_of_le_of_ne h ( Ne.symm hx ) ) ] ;
      · exact MeasureTheory.measure_mono_null ( fun ω hω => by linarith [ hω.out, Real.exp_pos ( -Y ω ) ] ) ( MeasureTheory.measure_empty )

/-
For positive x, the CDF of exp(-Y) matches the exponential distribution.
-/
lemma gumbel_to_exp_cdf_pos {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) [IsProbabilityMeasure μ] (Y : Ω → ℝ)
    (h_meas : Measurable Y)
    (hY : ∀ x, μ {ω | Y ω ≤ x} = ENNReal.ofReal (gumbel_cdf x))
    (x : ℝ) (hx : 0 < x) :
    μ {ω | Real.exp (-Y ω) ≤ x} = ENNReal.ofReal (1 - Real.exp (-x)) := by
      convert gumbel_to_exp_cdf μ Y h_meas hY x using 1;
      rw [ if_pos hx.le ]

/-
For non-positive x, the probability that exp(-Y) <= x is 0.
-/
lemma gumbel_to_exp_cdf_nonpos {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω) (Y : Ω → ℝ)
    (x : ℝ) (hx : x ≤ 0) :
    μ {ω | Real.exp (-Y ω) ≤ x} = 0 := by
      exact MeasureTheory.measure_mono_null ( fun ω hω => by linarith [ Real.exp_pos ( -Y ω ), hω.out ] ) ( MeasureTheory.measure_empty )
